DROP DATABASE IF EXISTS Imstagram;
CREATE DATABASE IF NOT EXISTS Imstagram;
USE Imstagram;

DROP TABLE IF EXISTS User; 

CREATE TABLE User (
     user_id INT NOT NULL AUTO_INCREMENT,
     first_name VARCHAR(30) NOT NULL,
     last_name VARCHAR(30) NOT NULL,
     birthday DATE,
     current_city VARCHAR(20) NOT NULL,
     hometown_city VARCHAR(20) NOT NULL,
     gender ENUM('male', 'female', 'others'),
     PRIMARY KEY (user_id)
);

INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Emma', 'Smith', '1991-06-26', 'New York', 'Los Angeles', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Ethan', 'Collins', '1982-08-22', 'San Francisco', 'San Diego', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Ava', 'Lee', '1981-03-12', 'Seattle', 'Miami', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Noah', 'Garcia', '1995-01-03', 'Chicago', 'Houston', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Mia', 'Scott', '1985-09-17', 'Boston', 'Philadelphia', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Liam', 'Johnson', '1995-09-14', 'Houston', 'San Francisco', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Ava', 'Garcia', '2000-12-28', 'Chicago', 'Mexico City', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Noah', 'Davis', '1992-03-21', 'Miami', 'New York', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Mia', 'Wilson', '1987-07-11', 'Los Angeles', 'Houston', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Ethan', 'Taylor', '1998-02-08', 'Miami', 'Miami', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Charlotte', 'Brown', '1991-04-05', 'New York', 'Chicago', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Aiden', 'Miller', '1996-11-30', 'Houston', 'San Francisco', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Amelia', 'Gonzalez', '2002-06-19', 'Chicago', 'Mexico City', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Caden', 'Rodriguez', '1993-09-02', 'Miami', 'New York', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Harper', 'Martinez', '1989-01-27', 'Los Angeles', 'Houston', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Logan', 'Lopez', '1998-06-18', 'San Francisco', 'Miami', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Avery', 'Hernandez', '1991-08-08', 'New York', 'Chicago', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Mason', 'Jackson', '1996-03-13', 'Houston', 'San Francisco', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Ella', 'Gomez', '2003-10-09', 'Chicago', 'Mexico City', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Jackson', 'Perez', '1992-12-22', 'Miami', 'New York', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Aria', 'Lee', '1990-05-16', 'Los Angeles', 'Houston', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('William', 'Garcia', '1997-11-11', 'San Francisco', 'Miami', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Evelyn', 'Davis', '2001-08-30', 'New York', 'Chicago', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Oliver', 'Wilson', '1988-10-05', 'Houston', 'San Francisco', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Scarlett', 'Taylor', '1999-05-27', 'Miami', 'New York', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Lucas', 'Brown', '1992-07-12', 'Los Angeles', 'Houston', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Aaliyah', 'Miller', '2002-04-20', 'San Francisco', 'Miami', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Ethan', 'Gonzalez', '1990-08-19', 'New York', 'Chicago', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Avery', 'Rodriguez', '1995-01-10', 'Houston', 'San Francisco', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Madison', 'Martinez', '1998-06-15', 'Miami', 'New York', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Logan', 'Lopez', '1993-02-09', 'Los Angeles', 'Houston', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Harper', 'Jackson', '2000-12-04', 'San Francisco', 'Miami', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Owen', 'Hernandez', '1992-04-27', 'New York', 'Chicago', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Lila', 'Perez', '2004-01-22', 'Houston', 'San Francisco', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Caleb', 'Gomez', '1987-11-08', 'New York', 'New York', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Isaac', 'Harris', '1994-03-28', 'Los Angeles', 'Houston', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Leah', 'Smith', '2002-09-07', 'San Francisco', 'Miami', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Gabriel', 'Garcia', '1991-07-02', 'New York', 'Chicago', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Zoe', 'Wilson', '1998-11-20', 'Houston', 'San Francisco', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Daniel', 'Taylor', '1993-12-30', 'Miami', 'New York', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Emily', 'Brown', '2005-02-01', 'Los Angeles', 'Houston', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Liam', 'Miller', '1996-06-18', 'San Francisco', 'Miami', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Grace', 'Gonzalez', '2000-03-15', 'Chicago', 'Chicago', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Mason', 'Rodriguez', '1988-09-26', 'Houston', 'San Francisco', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Chloe', 'Martinez', '1997-04-14', 'Miami', 'New York', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Jackson', 'Lopez', '1992-08-02', 'Los Angeles', 'Houston', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Aria', 'Jackson', '2001-01-27', 'San Francisco', 'Miami', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Benjamin', 'Hernandez', '1990-03-11', 'New York', 'Chicago', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Avery', 'Perez', '1995-09-10', 'Houston', 'San Francisco', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Emma', 'Gomez', '1998-02-28', 'Miami', 'New York', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Ethan', 'Lee', '1993-10-21', 'Los Angeles', 'Houston', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Olivia', 'Flores', '1996-07-23', 'San Francisco', 'Miami', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('William', 'Gonzalez', '1991-04-17', 'New York', 'Chicago', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Sophia', 'Torres', '2000-06-19', 'Houston', 'San Francisco', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Noah', 'Ramirez', '1989-08-08', 'Miami', 'New York', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Mia', 'Sanchez', '2004-11-12', 'Los Angeles', 'Houston', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Jacob', 'Nguyen', '1999-12-05', 'San Francisco', 'Miami', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Charlotte', 'Chen', '1992-05-09', 'New York', 'Chicago', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Lucas', 'Kim', '1997-09-03', 'Houston', 'San Francisco', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Ava', 'Patel', '2002-02-16', 'Miami', 'New York', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Logan', 'Singh', '1988-10-08', 'Los Angeles', 'Houston', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Harper', 'Kim', '1995-01-24', 'San Francisco', 'Miami', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Caleb', 'Choi', '1990-02-17', 'New York', 'Chicago', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Evelyn', 'Shah', '1998-08-30', 'Houston', 'San Francisco', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Owen', 'Ali', '1993-11-28', 'Miami', 'New York', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Amelia', 'Chen', '2001-01-22', 'Los Angeles', 'Houston', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Henry', 'Perez', '1992-12-03', 'San Francisco', 'Miami', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Alexander', 'Park', '1997-09-12', 'Houston', 'San Francisco', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Sofia', 'Chung', '1993-03-24', 'Miami', 'New York', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Benjamin', 'Huang', '1998-06-27', 'Los Angeles', 'Houston', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Chloe', 'Kim', '2000-11-18', 'San Francisco', 'Miami', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Daniel', 'Nguyen', '1995-02-10', 'New York', 'Chicago', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Madison', 'Khan', '1999-10-15', 'Houston', 'San Francisco', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Matthew', 'Li', '1988-07-14', 'Miami', 'New York', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Ella', 'Garcia', '2006-03-11', 'Los Angeles', 'Houston', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Samuel', 'Wu', '1994-04-22', 'San Francisco', 'Miami', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Avery', 'Lee', '1990-09-07', 'New York', 'Chicago', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Joseph', 'Fernandez', '1996-02-01', 'Houston', 'San Francisco', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Penelope', 'Lopez', '2001-07-29', 'Miami', 'New York', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('David', 'Wang', '1991-12-12', 'Los Angeles', 'Houston', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Aria', 'Tran', '1998-11-06', 'San Francisco', 'Miami', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Isabella', 'Ramos', '1997-05-02', 'New York', 'Chicago', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Arianna', 'Gomez', '1993-08-28', 'Miami', 'New York', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Nicholas', 'Chen', '1999-11-23', 'Los Angeles', 'Houston', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Victoria', 'Truong', '2005-02-07', 'San Francisco', 'Miami', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Andrew', 'Mendoza', '1990-01-16', 'New York', 'Chicago', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Natalie', 'Hernandez', '1998-12-30', 'Houston', 'San Francisco', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Ethan', 'Ng', '2004-06-21', 'Miami', 'New York', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Aurora', 'Rivera', '1992-09-04', 'Los Angeles', 'Houston', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Christopher', 'Chang', '1996-08-17', 'San Francisco', 'Miami', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Aaliyah', 'Nguyen', '2003-11-09', 'New York', 'Chicago', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Lucas', 'Harris', '1991-05-28', 'Houston', 'San Francisco', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Olivia', 'Lee', '2000-04-15', 'Miami', 'New York', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Ryan', 'Gonzalez', '1994-08-01', 'Los Angeles', 'Houston', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Grace', 'Wu', '2002-02-25', 'San Francisco', 'Miami', 'female');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Julian', 'Ramirez', '1993-09-22', 'New York', 'Chicago', 'male');
INSERT INTO User (first_name, last_name, birthday, current_city, hometown_city, gender) VALUES ('Emma', 'Lee', '1991-01-31', 'New York', 'Chicago', 'female');

DROP TABLE IF EXISTS Friends;

CREATE TABLE Friends(
    user1_id INT,
    user2_id INT,
    PRIMARY KEY(user1_id, user2_id),
    FOREIGN KEY(user1_id) REFERENCES User(user_id),
    FOREIGN KEY(user2_id) REFERENCES User(user_id));

INSERT INTO Friends (user1_id, user2_id) VALUES (1, 41);
INSERT INTO Friends (user1_id, user2_id) VALUES (11, 79);
INSERT INTO Friends (user1_id, user2_id) VALUES (5, 68);
INSERT INTO Friends (user1_id, user2_id) VALUES (30, 82);
INSERT INTO Friends (user1_id, user2_id) VALUES (25, 90);
INSERT INTO Friends (user1_id, user2_id) VALUES (50, 59);
INSERT INTO Friends (user1_id, user2_id) VALUES (4, 95);
INSERT INTO Friends (user1_id, user2_id) VALUES (2, 64);
INSERT INTO Friends (user1_id, user2_id) VALUES (12, 57);
INSERT INTO Friends (user1_id, user2_id) VALUES (48, 71);
INSERT INTO Friends (user1_id, user2_id) VALUES (34, 69);
INSERT INTO Friends (user1_id, user2_id) VALUES (3, 16);
INSERT INTO Friends (user1_id, user2_id) VALUES (27, 80);
INSERT INTO Friends (user1_id, user2_id) VALUES (18, 58);
INSERT INTO Friends (user1_id, user2_id) VALUES (21, 47);
INSERT INTO Friends (user1_id, user2_id) VALUES (14, 86);
INSERT INTO Friends (user1_id, user2_id) VALUES (23, 91);
INSERT INTO Friends (user1_id, user2_id) VALUES (38, 56);
INSERT INTO Friends (user1_id, user2_id) VALUES (43, 91);
INSERT INTO Friends (user1_id, user2_id) VALUES (10, 33);
INSERT INTO Friends (user1_id, user2_id) VALUES (8, 42);
INSERT INTO Friends (user1_id, user2_id) VALUES (9, 94);
INSERT INTO Friends (user1_id, user2_id) VALUES (12, 17);
INSERT INTO Friends (user1_id, user2_id) VALUES (18, 35);
INSERT INTO Friends (user1_id, user2_id) VALUES (5, 19);
INSERT INTO Friends (user1_id, user2_id) VALUES (40, 87);
INSERT INTO Friends (user1_id, user2_id) VALUES (35, 39);
INSERT INTO Friends (user1_id, user2_id) VALUES (54, 77);
INSERT INTO Friends (user1_id, user2_id) VALUES (10, 95);
INSERT INTO Friends (user1_id, user2_id) VALUES (30, 77);
INSERT INTO Friends (user1_id, user2_id) VALUES (16, 70);
INSERT INTO Friends (user1_id, user2_id) VALUES (24, 50);
INSERT INTO Friends (user1_id, user2_id) VALUES (29, 96);
INSERT INTO Friends (user1_id, user2_id) VALUES (7, 43);
INSERT INTO Friends (user1_id, user2_id) VALUES (46, 94);
INSERT INTO Friends (user1_id, user2_id) VALUES (49, 80);
INSERT INTO Friends (user1_id, user2_id) VALUES (11, 22);
INSERT INTO Friends (user1_id, user2_id) VALUES (39, 65);
INSERT INTO Friends (user1_id, user2_id) VALUES (22, 74);
INSERT INTO Friends (user1_id, user2_id) VALUES (6, 61);
INSERT INTO Friends (user1_id, user2_id) VALUES (31, 80);
INSERT INTO Friends (user1_id, user2_id) VALUES (6, 68);
INSERT INTO Friends (user1_id, user2_id) VALUES (14, 60);
INSERT INTO Friends (user1_id, user2_id) VALUES (53, 84);
INSERT INTO Friends (user1_id, user2_id) VALUES (4, 24);
INSERT INTO Friends (user1_id, user2_id) VALUES (7, 92);
INSERT INTO Friends (user1_id, user2_id) VALUES (15, 48);
INSERT INTO Friends (user1_id, user2_id) VALUES (32, 59);
INSERT INTO Friends (user1_id, user2_id) VALUES (19, 83);
INSERT INTO Friends (user1_id, user2_id) VALUES (13, 93);
INSERT INTO Friends (user1_id, user2_id) VALUES (37, 65);
INSERT INTO Friends (user1_id, user2_id) VALUES (15, 40);
INSERT INTO Friends (user1_id, user2_id) VALUES (20, 93);
INSERT INTO Friends (user1_id, user2_id) VALUES (25, 66);
INSERT INTO Friends (user1_id, user2_id) VALUES (51, 71);
INSERT INTO Friends (user1_id, user2_id) VALUES (41, 76);
INSERT INTO Friends (user1_id, user2_id) VALUES (31, 55);
INSERT INTO Friends (user1_id, user2_id) VALUES (33, 47);
INSERT INTO Friends (user1_id, user2_id) VALUES (9, 72);
INSERT INTO Friends (user1_id, user2_id) VALUES (28, 72);
INSERT INTO Friends (user1_id, user2_id) VALUES (42, 67);
INSERT INTO Friends (user1_id, user2_id) VALUES (32, 68);
INSERT INTO Friends (user1_id, user2_id) VALUES (28, 87);
INSERT INTO Friends (user1_id, user2_id) VALUES (52, 55);
INSERT INTO Friends (user1_id, user2_id) VALUES (1, 13);
INSERT INTO Friends (user1_id, user2_id) VALUES (21, 72);
INSERT INTO Friends (user1_id, user2_id) VALUES (50, 81);
INSERT INTO Friends (user1_id, user2_id) VALUES (37, 41);
INSERT INTO Friends (user1_id, user2_id) VALUES (63, 78);
INSERT INTO Friends (user1_id, user2_id) VALUES (52, 62);
INSERT INTO Friends (user1_id, user2_id) VALUES (3, 23);
INSERT INTO Friends (user1_id, user2_id) VALUES (44, 81);
INSERT INTO Friends (user1_id, user2_id) VALUES (8, 36);
INSERT INTO Friends (user1_id, user2_id) VALUES (26, 45);
INSERT INTO Friends (user1_id, user2_id) VALUES (17, 64);
INSERT INTO Friends (user1_id, user2_id) VALUES (54, 89);
INSERT INTO Friends (user1_id, user2_id) VALUES (36, 73);
INSERT INTO Friends (user1_id, user2_id) VALUES (45, 66);
INSERT INTO Friends (user1_id, user2_id) VALUES (62, 80);
INSERT INTO Friends (user1_id, user2_id) VALUES (46, 61);
INSERT INTO Friends (user1_id, user2_id) VALUES (34, 52);
INSERT INTO Friends (user1_id, user2_id) VALUES (26, 79);
INSERT INTO Friends (user1_id, user2_id) VALUES (67, 77);
INSERT INTO Friends (user1_id, user2_id) VALUES (75, 84);
INSERT INTO Friends (user1_id, user2_id) VALUES (63, 86);
INSERT INTO Friends (user1_id, user2_id) VALUES (27, 29);
INSERT INTO Friends (user1_id, user2_id) VALUES (70, 87);
INSERT INTO Friends (user1_id, user2_id) VALUES (59, 88);
INSERT INTO Friends (user1_id, user2_id) VALUES (76, 94);
INSERT INTO Friends (user1_id, user2_id) VALUES (42, 89);
INSERT INTO Friends (user1_id, user2_id) VALUES (51, 93);
INSERT INTO Friends (user1_id, user2_id) VALUES (67, 95);
INSERT INTO Friends (user1_id, user2_id) VALUES (60, 78);
INSERT INTO Friends (user1_id, user2_id) VALUES (36, 66);
INSERT INTO Friends (user1_id, user2_id) VALUES (74, 79);
INSERT INTO Friends (user1_id, user2_id) VALUES (57, 76);
INSERT INTO Friends (user1_id, user2_id) VALUES (16, 92);
INSERT INTO Friends (user1_id, user2_id) VALUES (53, 56);
INSERT INTO Friends (user1_id, user2_id) VALUES (61, 68);
INSERT INTO Friends (user1_id, user2_id) VALUES (48, 83);
INSERT INTO Friends (user1_id, user2_id) VALUES (43, 55);
INSERT INTO Friends (user1_id, user2_id) VALUES (58, 67);
INSERT INTO Friends (user1_id, user2_id) VALUES (82, 90);
INSERT INTO Friends (user1_id, user2_id) VALUES (24, 31);
INSERT INTO Friends (user1_id, user2_id) VALUES (38, 92);
INSERT INTO Friends (user1_id, user2_id) VALUES (20, 44);
INSERT INTO Friends (user1_id, user2_id) VALUES (69, 85);
INSERT INTO Friends (user1_id, user2_id) VALUES (23, 35);
INSERT INTO Friends (user1_id, user2_id) VALUES (49, 75);
INSERT INTO Friends (user1_id, user2_id) VALUES (60, 95);
INSERT INTO Friends (user1_id, user2_id) VALUES (71, 89);
INSERT INTO Friends (user1_id, user2_id) VALUES (75, 92);
INSERT INTO Friends (user1_id, user2_id) VALUES (40, 73);
INSERT INTO Friends (user1_id, user2_id) VALUES (46, 88);
INSERT INTO Friends (user1_id, user2_id) VALUES (77, 85);
INSERT INTO Friends (user1_id, user2_id) VALUES (28, 32);
INSERT INTO Friends (user1_id, user2_id) VALUES (13, 85);
INSERT INTO Friends (user1_id, user2_id) VALUES (54, 63);
INSERT INTO Friends (user1_id, user2_id) VALUES (45, 58);
INSERT INTO Friends (user1_id, user2_id) VALUES (19, 72);
INSERT INTO Friends (user1_id, user2_id) VALUES (22, 66);
INSERT INTO Friends (user1_id, user2_id) VALUES (14, 33);
INSERT INTO Friends (user1_id, user2_id) VALUES (2, 88);
INSERT INTO Friends (user1_id, user2_id) VALUES (11, 31);
INSERT INTO Friends (user1_id, user2_id) VALUES (3, 40);
INSERT INTO Friends (user1_id, user2_id) VALUES (43, 94);
INSERT INTO Friends (user1_id, user2_id) VALUES (37, 48);
INSERT INTO Friends (user1_id, user2_id) VALUES (16, 84);
INSERT INTO Friends (user1_id, user2_id) VALUES (10, 70);
INSERT INTO Friends (user1_id, user2_id) VALUES (19, 54);
INSERT INTO Friends (user1_id, user2_id) VALUES (11, 69);
INSERT INTO Friends (user1_id, user2_id) VALUES (2, 30);
INSERT INTO Friends (user1_id, user2_id) VALUES (43, 51);
INSERT INTO Friends (user1_id, user2_id) VALUES (30, 44);
INSERT INTO Friends (user1_id, user2_id) VALUES (10, 87);
INSERT INTO Friends (user1_id, user2_id) VALUES (35, 74);
INSERT INTO Friends (user1_id, user2_id) VALUES (12, 80);
INSERT INTO Friends (user1_id, user2_id) VALUES (1, 94);
INSERT INTO Friends (user1_id, user2_id) VALUES (25, 41);
INSERT INTO Friends (user1_id, user2_id) VALUES (37, 95);
INSERT INTO Friends (user1_id, user2_id) VALUES (12, 92);
INSERT INTO Friends (user1_id, user2_id) VALUES (4, 70);
INSERT INTO Friends (user1_id, user2_id) VALUES (41, 53);
INSERT INTO Friends (user1_id, user2_id) VALUES (3, 52);
INSERT INTO Friends (user1_id, user2_id) VALUES (21, 25);
INSERT INTO Friends (user1_id, user2_id) VALUES (9, 38);
INSERT INTO Friends (user1_id, user2_id) VALUES (7, 31);
INSERT INTO Friends (user1_id, user2_id) VALUES (27, 91);
INSERT INTO Friends (user1_id, user2_id) VALUES (32, 92);
INSERT INTO Friends (user1_id, user2_id) VALUES (1, 16);
INSERT INTO Friends (user1_id, user2_id) VALUES (22, 38);
INSERT INTO Friends (user1_id, user2_id) VALUES (27, 66);
INSERT INTO Friends (user1_id, user2_id) VALUES (28, 38);
INSERT INTO Friends (user1_id, user2_id) VALUES (45, 72);
INSERT INTO Friends (user1_id, user2_id) VALUES (14, 51);
INSERT INTO Friends (user1_id, user2_id) VALUES (41, 72);
INSERT INTO Friends (user1_id, user2_id) VALUES (46, 50);
INSERT INTO Friends (user1_id, user2_id) VALUES (14, 76);
INSERT INTO Friends (user1_id, user2_id) VALUES (21, 77);
INSERT INTO Friends (user1_id, user2_id) VALUES (32, 42);
INSERT INTO Friends (user1_id, user2_id) VALUES (33, 67);
INSERT INTO Friends (user1_id, user2_id) VALUES (29, 92);
INSERT INTO Friends (user1_id, user2_id) VALUES (22, 39);
INSERT INTO Friends (user1_id, user2_id) VALUES (24, 88);
INSERT INTO Friends (user1_id, user2_id) VALUES (35, 80);
INSERT INTO Friends (user1_id, user2_id) VALUES (7, 68);
INSERT INTO Friends (user1_id, user2_id) VALUES (55, 73);
INSERT INTO Friends (user1_id, user2_id) VALUES (26, 33);
INSERT INTO Friends (user1_id, user2_id) VALUES (2, 62);
INSERT INTO Friends (user1_id, user2_id) VALUES (44, 52);
INSERT INTO Friends (user1_id, user2_id) VALUES (36, 49);
INSERT INTO Friends (user1_id, user2_id) VALUES (18, 68);
INSERT INTO Friends (user1_id, user2_id) VALUES (18, 42);
INSERT INTO Friends (user1_id, user2_id) VALUES (13, 34);
INSERT INTO Friends (user1_id, user2_id) VALUES (56, 78);
INSERT INTO Friends (user1_id, user2_id) VALUES (60, 90);
INSERT INTO Friends (user1_id, user2_id) VALUES (48, 96);
INSERT INTO Friends (user1_id, user2_id) VALUES (34, 87);
INSERT INTO Friends (user1_id, user2_id) VALUES (24, 26);
INSERT INTO Friends (user1_id, user2_id) VALUES (23, 28);
INSERT INTO Friends (user1_id, user2_id) VALUES (65, 69);
INSERT INTO Friends (user1_id, user2_id) VALUES (17, 48);
INSERT INTO Friends (user1_id, user2_id) VALUES (8, 34);
INSERT INTO Friends (user1_id, user2_id) VALUES (55, 63);
INSERT INTO Friends (user1_id, user2_id) VALUES (26, 84);
INSERT INTO Friends (user1_id, user2_id) VALUES (61, 66);
INSERT INTO Friends (user1_id, user2_id) VALUES (60, 67);
INSERT INTO Friends (user1_id, user2_id) VALUES (36, 40);
INSERT INTO Friends (user1_id, user2_id) VALUES (65, 72);
INSERT INTO Friends (user1_id, user2_id) VALUES (6, 88);
INSERT INTO Friends (user1_id, user2_id) VALUES (4, 38);
INSERT INTO Friends (user1_id, user2_id) VALUES (6, 22);
INSERT INTO Friends (user1_id, user2_id) VALUES (47, 52);
INSERT INTO Friends (user1_id, user2_id) VALUES (56, 68);
INSERT INTO Friends (user1_id, user2_id) VALUES (23, 71);
INSERT INTO Friends (user1_id, user2_id) VALUES (62, 72);
INSERT INTO Friends (user1_id, user2_id) VALUES (15, 68);
INSERT INTO Friends (user1_id, user2_id) VALUES (75, 96);
INSERT INTO Friends (user1_id, user2_id) VALUES (15, 24);
INSERT INTO Friends (user1_id, user2_id) VALUES (59, 92);
INSERT INTO Friends (user1_id, user2_id) VALUES (49, 67);
INSERT INTO Friends (user1_id, user2_id) VALUES (29, 37);
INSERT INTO Friends (user1_id, user2_id) VALUES (44, 84);
INSERT INTO Friends (user1_id, user2_id) VALUES (57, 73);
INSERT INTO Friends (user1_id, user2_id) VALUES (8, 47);
INSERT INTO Friends (user1_id, user2_id) VALUES (9, 19);
INSERT INTO Friends (user1_id, user2_id) VALUES (17, 42);
INSERT INTO Friends (user1_id, user2_id) VALUES (39, 95);
INSERT INTO Friends (user1_id, user2_id) VALUES (63, 95);
INSERT INTO Friends (user1_id, user2_id) VALUES (76, 82);
INSERT INTO Friends (user1_id, user2_id) VALUES (50, 54);
INSERT INTO Friends (user1_id, user2_id) VALUES (71, 73);
INSERT INTO Friends (user1_id, user2_id) VALUES (25, 39);
INSERT INTO Friends (user1_id, user2_id) VALUES (67, 76);
INSERT INTO Friends (user1_id, user2_id) VALUES (33, 45);
INSERT INTO Friends (user1_id, user2_id) VALUES (81, 92);
INSERT INTO Friends (user1_id, user2_id) VALUES (46, 63);
INSERT INTO Friends (user1_id, user2_id) VALUES (20, 34);
INSERT INTO Friends (user1_id, user2_id) VALUES (28, 75);
INSERT INTO Friends (user1_id, user2_id) VALUES (13, 49);
INSERT INTO Friends (user1_id, user2_id) VALUES (5, 20);
INSERT INTO Friends (user1_id, user2_id) VALUES (5, 46);
INSERT INTO Friends (user1_id, user2_id) VALUES (77, 81);
INSERT INTO Friends (user1_id, user2_id) VALUES (58, 92);
INSERT INTO Friends (user1_id, user2_id) VALUES (80, 96);
INSERT INTO Friends (user1_id, user2_id) VALUES (53, 58);
INSERT INTO Friends (user1_id, user2_id) VALUES (79, 83);
INSERT INTO Friends (user1_id, user2_id) VALUES (85, 93);
INSERT INTO Friends (user1_id, user2_id) VALUES (64, 71);
INSERT INTO Friends (user1_id, user2_id) VALUES (50, 72);
INSERT INTO Friends (user1_id, user2_id) VALUES (59, 64);
INSERT INTO Friends (user1_id, user2_id) VALUES (57, 92);
INSERT INTO Friends (user1_id, user2_id) VALUES (61, 63);
INSERT INTO Friends (user1_id, user2_id) VALUES (26, 50);
INSERT INTO Friends (user1_id, user2_id) VALUES (75, 89);
INSERT INTO Friends (user1_id, user2_id) VALUES (81, 86);
INSERT INTO Friends (user1_id, user2_id) VALUES (39, 56);
INSERT INTO Friends (user1_id, user2_id) VALUES (19, 86);
INSERT INTO Friends (user1_id, user2_id) VALUES (85, 96);
INSERT INTO Friends (user1_id, user2_id) VALUES (90, 91);
INSERT INTO Friends (user1_id, user2_id) VALUES (54, 91);
INSERT INTO Friends (user1_id, user2_id) VALUES (7, 91);
INSERT INTO Friends (user1_id, user2_id) VALUES (9, 67);
INSERT INTO Friends (user1_id, user2_id) VALUES (56, 61);
INSERT INTO Friends (user1_id, user2_id) VALUES (16, 23);
INSERT INTO Friends (user1_id, user2_id) VALUES (73, 79);
INSERT INTO Friends (user1_id, user2_id) VALUES (41, 1);
INSERT INTO Friends (user1_id, user2_id) VALUES (79, 11);
INSERT INTO Friends (user1_id, user2_id) VALUES (68, 5);
INSERT INTO Friends (user1_id, user2_id) VALUES (82, 30);
INSERT INTO Friends (user1_id, user2_id) VALUES (90, 25);
INSERT INTO Friends (user1_id, user2_id) VALUES (59, 50);
INSERT INTO Friends (user1_id, user2_id) VALUES (95, 4);
INSERT INTO Friends (user1_id, user2_id) VALUES (64, 2);
INSERT INTO Friends (user1_id, user2_id) VALUES (57, 12);
INSERT INTO Friends (user1_id, user2_id) VALUES (71, 48);
INSERT INTO Friends (user1_id, user2_id) VALUES (69, 34);
INSERT INTO Friends (user1_id, user2_id) VALUES (16, 3);
INSERT INTO Friends (user1_id, user2_id) VALUES (80, 27);
INSERT INTO Friends (user1_id, user2_id) VALUES (58, 18);
INSERT INTO Friends (user1_id, user2_id) VALUES (47, 21);
INSERT INTO Friends (user1_id, user2_id) VALUES (86, 14);
INSERT INTO Friends (user1_id, user2_id) VALUES (91, 23);
INSERT INTO Friends (user1_id, user2_id) VALUES (56, 38);
INSERT INTO Friends (user1_id, user2_id) VALUES (91, 43);
INSERT INTO Friends (user1_id, user2_id) VALUES (33, 10);
INSERT INTO Friends (user1_id, user2_id) VALUES (42, 8);
INSERT INTO Friends (user1_id, user2_id) VALUES (94, 9);
INSERT INTO Friends (user1_id, user2_id) VALUES (17, 12);
INSERT INTO Friends (user1_id, user2_id) VALUES (35, 18);
INSERT INTO Friends (user1_id, user2_id) VALUES (19, 5);
INSERT INTO Friends (user1_id, user2_id) VALUES (87, 40);
INSERT INTO Friends (user1_id, user2_id) VALUES (39, 35);
INSERT INTO Friends (user1_id, user2_id) VALUES (77, 54);
INSERT INTO Friends (user1_id, user2_id) VALUES (95, 10);
INSERT INTO Friends (user1_id, user2_id) VALUES (77, 30);
INSERT INTO Friends (user1_id, user2_id) VALUES (70, 16);
INSERT INTO Friends (user1_id, user2_id) VALUES (50, 24);
INSERT INTO Friends (user1_id, user2_id) VALUES (96, 29);
INSERT INTO Friends (user1_id, user2_id) VALUES (43, 7);
INSERT INTO Friends (user1_id, user2_id) VALUES (94, 46);
INSERT INTO Friends (user1_id, user2_id) VALUES (80, 49);
INSERT INTO Friends (user1_id, user2_id) VALUES (22, 11);
INSERT INTO Friends (user1_id, user2_id) VALUES (65, 39);
INSERT INTO Friends (user1_id, user2_id) VALUES (74, 22);
INSERT INTO Friends (user1_id, user2_id) VALUES (61, 6);
INSERT INTO Friends (user1_id, user2_id) VALUES (80, 31);
INSERT INTO Friends (user1_id, user2_id) VALUES (68, 6);
INSERT INTO Friends (user1_id, user2_id) VALUES (60, 14);
INSERT INTO Friends (user1_id, user2_id) VALUES (84, 53);
INSERT INTO Friends (user1_id, user2_id) VALUES (24, 4);
INSERT INTO Friends (user1_id, user2_id) VALUES (92, 7);
INSERT INTO Friends (user1_id, user2_id) VALUES (48, 15);
INSERT INTO Friends (user1_id, user2_id) VALUES (59, 32);
INSERT INTO Friends (user1_id, user2_id) VALUES (83, 19);
INSERT INTO Friends (user1_id, user2_id) VALUES (93, 13);
INSERT INTO Friends (user1_id, user2_id) VALUES (65, 37);
INSERT INTO Friends (user1_id, user2_id) VALUES (40, 15);
INSERT INTO Friends (user1_id, user2_id) VALUES (93, 20);
INSERT INTO Friends (user1_id, user2_id) VALUES (66, 25);
INSERT INTO Friends (user1_id, user2_id) VALUES (71, 51);
INSERT INTO Friends (user1_id, user2_id) VALUES (76, 41);
INSERT INTO Friends (user1_id, user2_id) VALUES (55, 31);
INSERT INTO Friends (user1_id, user2_id) VALUES (47, 33);
INSERT INTO Friends (user1_id, user2_id) VALUES (72, 9);
INSERT INTO Friends (user1_id, user2_id) VALUES (72, 28);
INSERT INTO Friends (user1_id, user2_id) VALUES (67, 42);
INSERT INTO Friends (user1_id, user2_id) VALUES (68, 32);
INSERT INTO Friends (user1_id, user2_id) VALUES (87, 28);
INSERT INTO Friends (user1_id, user2_id) VALUES (55, 52);
INSERT INTO Friends (user1_id, user2_id) VALUES (13, 1);
INSERT INTO Friends (user1_id, user2_id) VALUES (72, 21);
INSERT INTO Friends (user1_id, user2_id) VALUES (81, 50);
INSERT INTO Friends (user1_id, user2_id) VALUES (41, 37);
INSERT INTO Friends (user1_id, user2_id) VALUES (78, 63);
INSERT INTO Friends (user1_id, user2_id) VALUES (62, 52);
INSERT INTO Friends (user1_id, user2_id) VALUES (23, 3);
INSERT INTO Friends (user1_id, user2_id) VALUES (81, 44);
INSERT INTO Friends (user1_id, user2_id) VALUES (36, 8);
INSERT INTO Friends (user1_id, user2_id) VALUES (45, 26);
INSERT INTO Friends (user1_id, user2_id) VALUES (64, 17);
INSERT INTO Friends (user1_id, user2_id) VALUES (89, 54);
INSERT INTO Friends (user1_id, user2_id) VALUES (73, 36);
INSERT INTO Friends (user1_id, user2_id) VALUES (66, 45);
INSERT INTO Friends (user1_id, user2_id) VALUES (80, 62);
INSERT INTO Friends (user1_id, user2_id) VALUES (61, 46);
INSERT INTO Friends (user1_id, user2_id) VALUES (52, 34);
INSERT INTO Friends (user1_id, user2_id) VALUES (79, 26);
INSERT INTO Friends (user1_id, user2_id) VALUES (77, 67);
INSERT INTO Friends (user1_id, user2_id) VALUES (84, 75);
INSERT INTO Friends (user1_id, user2_id) VALUES (86, 63);
INSERT INTO Friends (user1_id, user2_id) VALUES (29, 27);
INSERT INTO Friends (user1_id, user2_id) VALUES (87, 70);
INSERT INTO Friends (user1_id, user2_id) VALUES (88, 59);
INSERT INTO Friends (user1_id, user2_id) VALUES (94, 76);
INSERT INTO Friends (user1_id, user2_id) VALUES (89, 42);
INSERT INTO Friends (user1_id, user2_id) VALUES (93, 51);
INSERT INTO Friends (user1_id, user2_id) VALUES (95, 67);
INSERT INTO Friends (user1_id, user2_id) VALUES (78, 60);
INSERT INTO Friends (user1_id, user2_id) VALUES (66, 36);
INSERT INTO Friends (user1_id, user2_id) VALUES (79, 74);
INSERT INTO Friends (user1_id, user2_id) VALUES (76, 57);
INSERT INTO Friends (user1_id, user2_id) VALUES (92, 16);
INSERT INTO Friends (user1_id, user2_id) VALUES (56, 53);
INSERT INTO Friends (user1_id, user2_id) VALUES (68, 61);
INSERT INTO Friends (user1_id, user2_id) VALUES (83, 48);
INSERT INTO Friends (user1_id, user2_id) VALUES (55, 43);
INSERT INTO Friends (user1_id, user2_id) VALUES (67, 58);
INSERT INTO Friends (user1_id, user2_id) VALUES (90, 82);
INSERT INTO Friends (user1_id, user2_id) VALUES (31, 24);
INSERT INTO Friends (user1_id, user2_id) VALUES (92, 38);
INSERT INTO Friends (user1_id, user2_id) VALUES (44, 20);
INSERT INTO Friends (user1_id, user2_id) VALUES (85, 69);
INSERT INTO Friends (user1_id, user2_id) VALUES (35, 23);
INSERT INTO Friends (user1_id, user2_id) VALUES (75, 49);
INSERT INTO Friends (user1_id, user2_id) VALUES (95, 60);
INSERT INTO Friends (user1_id, user2_id) VALUES (89, 71);
INSERT INTO Friends (user1_id, user2_id) VALUES (92, 75);
INSERT INTO Friends (user1_id, user2_id) VALUES (73, 40);
INSERT INTO Friends (user1_id, user2_id) VALUES (88, 46);
INSERT INTO Friends (user1_id, user2_id) VALUES (85, 77);
INSERT INTO Friends (user1_id, user2_id) VALUES (32, 28);
INSERT INTO Friends (user1_id, user2_id) VALUES (85, 13);
INSERT INTO Friends (user1_id, user2_id) VALUES (63, 54);
INSERT INTO Friends (user1_id, user2_id) VALUES (58, 45);
INSERT INTO Friends (user1_id, user2_id) VALUES (72, 19);
INSERT INTO Friends (user1_id, user2_id) VALUES (66, 22);
INSERT INTO Friends (user1_id, user2_id) VALUES (33, 14);
INSERT INTO Friends (user1_id, user2_id) VALUES (88, 2);
INSERT INTO Friends (user1_id, user2_id) VALUES (31, 11);
INSERT INTO Friends (user1_id, user2_id) VALUES (40, 3);
INSERT INTO Friends (user1_id, user2_id) VALUES (94, 43);
INSERT INTO Friends (user1_id, user2_id) VALUES (48, 37);
INSERT INTO Friends (user1_id, user2_id) VALUES (84, 16);
INSERT INTO Friends (user1_id, user2_id) VALUES (70, 10);
INSERT INTO Friends (user1_id, user2_id) VALUES (54, 19);
INSERT INTO Friends (user1_id, user2_id) VALUES (69, 11);
INSERT INTO Friends (user1_id, user2_id) VALUES (30, 2);
INSERT INTO Friends (user1_id, user2_id) VALUES (51, 43);
INSERT INTO Friends (user1_id, user2_id) VALUES (44, 30);
INSERT INTO Friends (user1_id, user2_id) VALUES (87, 10);
INSERT INTO Friends (user1_id, user2_id) VALUES (74, 35);
INSERT INTO Friends (user1_id, user2_id) VALUES (80, 12);
INSERT INTO Friends (user1_id, user2_id) VALUES (94, 1);
INSERT INTO Friends (user1_id, user2_id) VALUES (41, 25);
INSERT INTO Friends (user1_id, user2_id) VALUES (95, 37);
INSERT INTO Friends (user1_id, user2_id) VALUES (92, 12);
INSERT INTO Friends (user1_id, user2_id) VALUES (70, 4);
INSERT INTO Friends (user1_id, user2_id) VALUES (53, 41);
INSERT INTO Friends (user1_id, user2_id) VALUES (52, 3);
INSERT INTO Friends (user1_id, user2_id) VALUES (25, 21);
INSERT INTO Friends (user1_id, user2_id) VALUES (38, 9);
INSERT INTO Friends (user1_id, user2_id) VALUES (31, 7);
INSERT INTO Friends (user1_id, user2_id) VALUES (91, 27);
INSERT INTO Friends (user1_id, user2_id) VALUES (92, 32);
INSERT INTO Friends (user1_id, user2_id) VALUES (16, 1);
INSERT INTO Friends (user1_id, user2_id) VALUES (38, 22);
INSERT INTO Friends (user1_id, user2_id) VALUES (66, 27);
INSERT INTO Friends (user1_id, user2_id) VALUES (38, 28);
INSERT INTO Friends (user1_id, user2_id) VALUES (72, 45);
INSERT INTO Friends (user1_id, user2_id) VALUES (51, 14);
INSERT INTO Friends (user1_id, user2_id) VALUES (72, 41);
INSERT INTO Friends (user1_id, user2_id) VALUES (50, 46);
INSERT INTO Friends (user1_id, user2_id) VALUES (76, 14);
INSERT INTO Friends (user1_id, user2_id) VALUES (77, 21);
INSERT INTO Friends (user1_id, user2_id) VALUES (42, 32);
INSERT INTO Friends (user1_id, user2_id) VALUES (67, 33);
INSERT INTO Friends (user1_id, user2_id) VALUES (92, 29);
INSERT INTO Friends (user1_id, user2_id) VALUES (39, 22);
INSERT INTO Friends (user1_id, user2_id) VALUES (88, 24);
INSERT INTO Friends (user1_id, user2_id) VALUES (80, 35);
INSERT INTO Friends (user1_id, user2_id) VALUES (68, 7);
INSERT INTO Friends (user1_id, user2_id) VALUES (73, 55);
INSERT INTO Friends (user1_id, user2_id) VALUES (33, 26);
INSERT INTO Friends (user1_id, user2_id) VALUES (62, 2);
INSERT INTO Friends (user1_id, user2_id) VALUES (52, 44);
INSERT INTO Friends (user1_id, user2_id) VALUES (49, 36);
INSERT INTO Friends (user1_id, user2_id) VALUES (68, 18);
INSERT INTO Friends (user1_id, user2_id) VALUES (42, 18);
INSERT INTO Friends (user1_id, user2_id) VALUES (34, 13);
INSERT INTO Friends (user1_id, user2_id) VALUES (78, 56);
INSERT INTO Friends (user1_id, user2_id) VALUES (90, 60);
INSERT INTO Friends (user1_id, user2_id) VALUES (96, 48);
INSERT INTO Friends (user1_id, user2_id) VALUES (87, 34);
INSERT INTO Friends (user1_id, user2_id) VALUES (26, 24);
INSERT INTO Friends (user1_id, user2_id) VALUES (28, 23);
INSERT INTO Friends (user1_id, user2_id) VALUES (69, 65);
INSERT INTO Friends (user1_id, user2_id) VALUES (48, 17);
INSERT INTO Friends (user1_id, user2_id) VALUES (34, 8);
INSERT INTO Friends (user1_id, user2_id) VALUES (63, 55);
INSERT INTO Friends (user1_id, user2_id) VALUES (84, 26);
INSERT INTO Friends (user1_id, user2_id) VALUES (66, 61);
INSERT INTO Friends (user1_id, user2_id) VALUES (67, 60);
INSERT INTO Friends (user1_id, user2_id) VALUES (40, 36);
INSERT INTO Friends (user1_id, user2_id) VALUES (72, 65);
INSERT INTO Friends (user1_id, user2_id) VALUES (88, 6);
INSERT INTO Friends (user1_id, user2_id) VALUES (38, 4);
INSERT INTO Friends (user1_id, user2_id) VALUES (22, 6);
INSERT INTO Friends (user1_id, user2_id) VALUES (52, 47);
INSERT INTO Friends (user1_id, user2_id) VALUES (68, 56);
INSERT INTO Friends (user1_id, user2_id) VALUES (71, 23);
INSERT INTO Friends (user1_id, user2_id) VALUES (72, 62);
INSERT INTO Friends (user1_id, user2_id) VALUES (68, 15);
INSERT INTO Friends (user1_id, user2_id) VALUES (96, 75);
INSERT INTO Friends (user1_id, user2_id) VALUES (24, 15);
INSERT INTO Friends (user1_id, user2_id) VALUES (92, 59);
INSERT INTO Friends (user1_id, user2_id) VALUES (67, 49);
INSERT INTO Friends (user1_id, user2_id) VALUES (37, 29);
INSERT INTO Friends (user1_id, user2_id) VALUES (84, 44);
INSERT INTO Friends (user1_id, user2_id) VALUES (73, 57);
INSERT INTO Friends (user1_id, user2_id) VALUES (47, 8);
INSERT INTO Friends (user1_id, user2_id) VALUES (19, 9);
INSERT INTO Friends (user1_id, user2_id) VALUES (42, 17);
INSERT INTO Friends (user1_id, user2_id) VALUES (95, 39);
INSERT INTO Friends (user1_id, user2_id) VALUES (95, 63);
INSERT INTO Friends (user1_id, user2_id) VALUES (82, 76);
INSERT INTO Friends (user1_id, user2_id) VALUES (54, 50);
INSERT INTO Friends (user1_id, user2_id) VALUES (73, 71);
INSERT INTO Friends (user1_id, user2_id) VALUES (39, 25);
INSERT INTO Friends (user1_id, user2_id) VALUES (76, 67);
INSERT INTO Friends (user1_id, user2_id) VALUES (45, 33);
INSERT INTO Friends (user1_id, user2_id) VALUES (92, 81);
INSERT INTO Friends (user1_id, user2_id) VALUES (63, 46);
INSERT INTO Friends (user1_id, user2_id) VALUES (34, 20);
INSERT INTO Friends (user1_id, user2_id) VALUES (75, 28);
INSERT INTO Friends (user1_id, user2_id) VALUES (49, 13);
INSERT INTO Friends (user1_id, user2_id) VALUES (20, 5);
INSERT INTO Friends (user1_id, user2_id) VALUES (46, 5);
INSERT INTO Friends (user1_id, user2_id) VALUES (81, 77);
INSERT INTO Friends (user1_id, user2_id) VALUES (92, 58);
INSERT INTO Friends (user1_id, user2_id) VALUES (96, 80);
INSERT INTO Friends (user1_id, user2_id) VALUES (58, 53);
INSERT INTO Friends (user1_id, user2_id) VALUES (83, 79);
INSERT INTO Friends (user1_id, user2_id) VALUES (93, 85);
INSERT INTO Friends (user1_id, user2_id) VALUES (71, 64);
INSERT INTO Friends (user1_id, user2_id) VALUES (72, 50);
INSERT INTO Friends (user1_id, user2_id) VALUES (64, 59);
INSERT INTO Friends (user1_id, user2_id) VALUES (92, 57);
INSERT INTO Friends (user1_id, user2_id) VALUES (63, 61);
INSERT INTO Friends (user1_id, user2_id) VALUES (50, 26);
INSERT INTO Friends (user1_id, user2_id) VALUES (89, 75);
INSERT INTO Friends (user1_id, user2_id) VALUES (86, 81);
INSERT INTO Friends (user1_id, user2_id) VALUES (56, 39);
INSERT INTO Friends (user1_id, user2_id) VALUES (86, 19);
INSERT INTO Friends (user1_id, user2_id) VALUES (96, 85);
INSERT INTO Friends (user1_id, user2_id) VALUES (91, 90);
INSERT INTO Friends (user1_id, user2_id) VALUES (91, 54);
INSERT INTO Friends (user1_id, user2_id) VALUES (91, 7);
INSERT INTO Friends (user1_id, user2_id) VALUES (67, 9);
INSERT INTO Friends (user1_id, user2_id) VALUES (61, 56);
INSERT INTO Friends (user1_id, user2_id) VALUES (23, 16);
INSERT INTO Friends (user1_id, user2_id) VALUES (79, 73);

DROP TABLE IF EXISTS Photo;

CREATE TABLE Photo (
    photo_id INT NOT NULL AUTO_INCREMENT,
    city VARCHAR(20) NOT NULL,
    PRIMARY KEY (photo_id)
);

INSERT INTO Photo (city) VALUES ('Mumbai');
INSERT INTO Photo (city) VALUES ('Taipei');
INSERT INTO Photo (city) VALUES ('Hong Kong');
INSERT INTO Photo (city) VALUES ('Ho Chi Minh City');
INSERT INTO Photo (city) VALUES ('New York');
INSERT INTO Photo (city) VALUES ('Portland');
INSERT INTO Photo (city) VALUES ('Shanghai');
INSERT INTO Photo (city) VALUES ('Boston');
INSERT INTO Photo (city) VALUES ('San Francisco');
INSERT INTO Photo (city) VALUES ('Chicago');
INSERT INTO Photo (city) VALUES ('Seattle');
INSERT INTO Photo (city) VALUES ('Los Angeles');
INSERT INTO Photo (city) VALUES ('Miami');
INSERT INTO Photo (city) VALUES ('Delhi');
INSERT INTO Photo (city) VALUES ('Austin');
INSERT INTO Photo (city) VALUES ('Seattle');
INSERT INTO Photo (city) VALUES ('Santo Domingo');
INSERT INTO Photo (city) VALUES ('Las Vegas');
INSERT INTO Photo (city) VALUES ('New York');
INSERT INTO Photo (city) VALUES ('San Diego');
INSERT INTO Photo (city) VALUES ('Houston');
INSERT INTO Photo (city) VALUES ('Delhi');
INSERT INTO Photo (city) VALUES ('San Francisco');
INSERT INTO Photo (city) VALUES ('Hong Kong');
INSERT INTO Photo (city) VALUES ('Mumbai');
INSERT INTO Photo (city) VALUES ('Tijuana');
INSERT INTO Photo (city) VALUES ('Chicago');
INSERT INTO Photo (city) VALUES ('Ho Chi Minh City');
INSERT INTO Photo (city) VALUES ('Taipei');
INSERT INTO Photo (city) VALUES ('San Diego');
INSERT INTO Photo (city) VALUES ('Mexico City');
INSERT INTO Photo (city) VALUES ('Seoul');
INSERT INTO Photo (city) VALUES ('San Juan');
INSERT INTO Photo (city) VALUES ('Las Vegas');
INSERT INTO Photo (city) VALUES ('Portland');
INSERT INTO Photo (city) VALUES ('Dallas');
INSERT INTO Photo (city) VALUES ('Los Angeles');
INSERT INTO Photo (city) VALUES ('Seattle');
INSERT INTO Photo (city) VALUES ('New Delhi');
INSERT INTO Photo (city) VALUES ('San Francisco');
INSERT INTO Photo (city) VALUES ('Hong Kong');
INSERT INTO Photo (city) VALUES ('Delhi');
INSERT INTO Photo (city) VALUES ('Boston');
INSERT INTO Photo (city) VALUES ('Chicago');
INSERT INTO Photo (city) VALUES ('Austin');
INSERT INTO Photo (city) VALUES ('Orlando');
INSERT INTO Photo (city) VALUES ('San Juan');
INSERT INTO Photo (city) VALUES ('Santo Domingo');
INSERT INTO Photo (city) VALUES ('Mumbai');
INSERT INTO Photo (city) VALUES ('Houston');
INSERT INTO Photo (city) VALUES ('Taipei');
INSERT INTO Photo (city) VALUES ('Portland');
INSERT INTO Photo (city) VALUES ('Seattle');
INSERT INTO Photo (city) VALUES ('Shanghai');
INSERT INTO Photo (city) VALUES ('Ho Chi Minh City');
INSERT INTO Photo (city) VALUES ('New York');
INSERT INTO Photo (city) VALUES ('Las Vegas');
INSERT INTO Photo (city) VALUES ('Miami');
INSERT INTO Photo (city) VALUES ('San Francisco');
INSERT INTO Photo (city) VALUES ('Tijuana');
INSERT INTO Photo (city) VALUES ('Hong Kong');
INSERT INTO Photo (city) VALUES ('Delhi');
INSERT INTO Photo (city) VALUES ('Seattle');
INSERT INTO Photo (city) VALUES ('Chicago');
INSERT INTO Photo (city) VALUES ('Los Angeles');
INSERT INTO Photo (city) VALUES ('Austin');
INSERT INTO Photo (city) VALUES ('San Diego');
INSERT INTO Photo (city) VALUES ('San Juan');
INSERT INTO Photo (city) VALUES ('Santo Domingo');
INSERT INTO Photo (city) VALUES ('New York');
INSERT INTO Photo (city) VALUES ('Mumbai');
INSERT INTO Photo (city) VALUES ('Portland');
INSERT INTO Photo (city) VALUES ('Houston');
INSERT INTO Photo (city) VALUES ('Taipei');
INSERT INTO Photo (city) VALUES ('San Francisco');

DROP TABLE IF EXISTS Tagged_photo_user;

CREATE TABLE Tagged_photo_user (
    photo_id INT NOT NULL,
    tagged_photo_user_id INT NOT NULL,
    PRIMARY KEY(photo_id, tagged_photo_user_id)
);

INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (1,8);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (1,35);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (1,62);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (1,11);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (1,95);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (1,67);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (1,84);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (2,90);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (2,26);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (2,70);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (2,15);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (2,63);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (2,56);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (2,48);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (3,72);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (3,53);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (3,13);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (3,5);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (3,85);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (3,17);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (4,31);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (4, 46);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (4,24);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (4,68);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (4,26);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (4,80);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (5,2);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (5,61);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (5,92);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (5, 50);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (5,29);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (6,78);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (6,21);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (6,89);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (6,57);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (6,91);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (6,25);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (6,28);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (7,97);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (7,76);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (7,82);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (7,65);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (7,51);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (7,42);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (8,54);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (8,4);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (8,75);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (8,52);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (8,88);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (8,58);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (8,30);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (9,44);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (9,16);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (9,34);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (9,55);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (9,73);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (10,71);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (10,64);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (10,43);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (10,94);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (10,9);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (10,32);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (11,23);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (11,40);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (11,7);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (11,36);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (11,69);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (11,19);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (11,74);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (12,39);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (12,45);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (12,60);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (12,33);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (12,41);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (12,77);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (13,12);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (13,93);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (13,27);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (13,38);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (13,14);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (13,87);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (13,49);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (14,79);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (14,81);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (14,37);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (14,47);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (14,10);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (14,59);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (15,22);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (15,18);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (15,66);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (15,3);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (15,86);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (15,96);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (16,83);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (16,20);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (16,6);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (16,1);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (16,50);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (17,67);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (17,73);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (17,31);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (17,34);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (17,14);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (17,80);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (18,39);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (18,57);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (18,32);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (18,61);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (18,25);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (18,10);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (19,90);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (19,78);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (19,54);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (19,20);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (19,47);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (19,28);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (20,56);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (20,74);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (20,38);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (20,94);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (20,17);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (21,22);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (21,3);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (21,29);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (21,53);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (21,79);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (21,15);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (21,64);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (22,40);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (22,85);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (22,70);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (22,87);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (22,7);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (22,91);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (22,46);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (23,41);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (23,44);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (23,51);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (23,71);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (23,66);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (23,58);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (23,84);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (24,45);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (24,52);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (24,68);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (24,69);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (24,11);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (24,36);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (24,26);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (25,5);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (25,95);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (25,63);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (25,30);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (25,12);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (25,37);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (25,83);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (26,8);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (26,76);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (26,21);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (26,27);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (26,62);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (26,16);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (26,55);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (27,2);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (27,49);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (27,89);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (27,92);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (27,77);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (28,65);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (28,60);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (28,72);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (28,9);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (28,42);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (28,50);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (29,24);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (29,43);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (29,75);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (29,35);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (29,81);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (29,18);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (29,97);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (30,4);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (30,33);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (30,59);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (30,1);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (30,48);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (31,88);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (31,19);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (31,6);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (31,23);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (31,13);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (32,28);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (32,74);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (32,60);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (32,97);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (32,56);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (32,24);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (33,40);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (33,78);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (33,31);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (33,11);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (33,66);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (33,58);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (34,62);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (34,86);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (34,48);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (34,77);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (34,29);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (34,52);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (35,92);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (35,71);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (35,44);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (35,90);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (35,64);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (35,19);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (35,51);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (36,37);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (36,29);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (36,81);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (37,11);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (37,13);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (37,58);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (37,75);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (38,60);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (38,43);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (39,68);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (39,42);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (39,93);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (40,96);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (40,56);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (40,63);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (41,69);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (41,4);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (41,40);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (42,70);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (42,52);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (42,39);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (43,27);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (43,88);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (43,82);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (43,19);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (44,59);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (44,71);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (45,69);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (45,10);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (46,93);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (46,49);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (46,52);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (46,23);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (47,87);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (47,77);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (47,18);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (48,81);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (48,48);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (48,90);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (49,92);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (49,63);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (49,74);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (49,9);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (50,72);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (50,49);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (50,58);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (50,5);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (51,56);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (51,64);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (52,58);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (52,4);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (52,62);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (53,61);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (53,52);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (53,50);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (54,27);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (54,88);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (55,34);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (55,80);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (55,59);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (56,39);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (56,70);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (56,53);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (57,95);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (57,28);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (57,54);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (58,24);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (58,38);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (59,59);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (59,70);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (59,13);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (59,67);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (59,11);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (60,94);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (60,12);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (60,47);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (60,21);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (61,81);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (61,57);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (61,23);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (62,78);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (62,68);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (63,91);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (63,62);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (64,37);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (64,29);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (64,79);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (64,7);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (65,31);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (65,12);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (65,78);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (65,88);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (66,32);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (66,89);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (67,23);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (67,70);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (68,60);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (68,95);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (68,78);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (69,11);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (69,24);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (69,33);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (69,90);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (70,41);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (70,36);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (70,2);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (70,78);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (71,58);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (71,61);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (71,25);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (72,87);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (72,7);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (73,11);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (73,92);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (73,41);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (73,39);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (74,19);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (74,84);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (75,55);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (75,24);
INSERT INTO Tagged_photo_user (photo_id, tagged_photo_user_id) VALUES (75,14);